publishdir = "public"
static = "/static"
builddrafts = false
# Replace this with your website URL
baseurl = "https://10.16.3.226/DBGroup"
canonifyurls = true
theme = "academic-group"
title = "DBGroup"
math = true
copyright = "&copy; DB Group, 2020 "
enableRobotsTXT = true

[taxonomies]
category = "categories"
tag = "tags"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  description = "Website of research group"
  author = "DBGRoup"
  email = "tangb3@sustech.edu.cn"
 # youtube = "https://www.youtube.com/channel/UCd1ftkOXIQ8MstIHosEDdaw/"
  address = 'Room 1007, A7, iPark No.1088 Xueyuan Blvd., Nanshan District, Shenzhen 518055, P.R. China'
  slogan_icon = "icon-spsbrats_logo"
  slogan_text = "DBGroup"
  custom_css = ["biaslab.css"]
  landing_heading = ""
  landing_description = ""
 # landing_description = "Automating the development of novel signal processing and control systems through <span style=\"white-space: nowrap;\">neuro-inspired</span> <span style=\"white-space: nowrap;\">free-energy</span> minimizing agents"
  positions_available = true

  [params.logo]
    image = "img/DBGroup_logo.jpg"
    url = "/#home"

  [[params.navbar_hierarchy]]
    name = "CSE"
    link = "http://cse.sustech.edu.cn/"
    position = 1

  [[params.navbar_hierarchy]]
    name = "DBGroup"
    link = "/"
    position = 2

  [[params.sponsors]]
    name = "Huawei"
    link = "https://e.huawei.com/cn/products/cloud-computing-dc/gaussdb"
    image = "/own_img/huawei.jpg"
#  [[params.sponsors]]
#    name = "Tencent"
#    link = "http://www.tencent.com.cn"
#    image = "/img/sponsors/tencent.jpg"

  # Selected Publications section.
  [params.publications_selected]
    detailed_list = true
    title = "Selected Publications"
    subtitle = ""

  # Publications section.
  # Section will only be displayed if there are publications in `content/publication/`.
  [params.members]
    count = 8
  [params.publications]
    count = 5
    detailed_list = false
    title = "Publications"
    subtitle = ""
    str_all = "More Publications"

  # Posts section.
  # Section will only be displayed if there are posts in `content/post/`.
  [params.posts]
    count = 2
    title = "Blog"
    subtitle = ""
    str_all = "More Posts"
    str_read_more = "Read more"

  # Projects section.
  # Section will only be displayed if there are projects in `content/project/`.
  [params.projects]
    title = "Projects"
    subtitle = ""
    count = 4
    str_all = "More Projects"

  # Vacancies section
  # Section will only be displayed if there are valid vacancies in `content/vacancy`
#  [params.open_projects]
#    title = "Open projects"
#    subtitle = ""
#    count = 3
#    str_all = "All open projects"

  # Contact section.
  [params.contact]
    enable = true
    title = "Contact"
    subtitle = ""
    autolink = false  # Automatically link email and phone?

  # Navigation Links
  #   The weight parameter defines the order that the links will appear in.

  [[menu.main]]
    name = "Home"
    url = "/#home"
    weight = 1

  [[menu.main]]
    name = "Publications"
    url = "/#publications"
    parent="research"
    weight = 2

  [[menu.main]]
    name = "Join Us"
    url = "/Join-us"

    weight = 6

  [[menu.main]]
    name = "Research"
    url="/#research"
    weight = 2
    identifier = "research"

  [[menu.main]]
    name = "Projects"
    url = "/#projects"
    parent = "research"
    weight = 2


  [[menu.main]]
    name = "Team"
    url = "/#members"
    weight = 4



  [[menu.main]]
    name = "Contact"
    url = "/#contact"
    weight = 7

  [[menu.main]]
    name = "Teaching"
    url = "http://mooc1.chaoxing.com/course/214395507.html"
    weight = 3

      [[menu.main]]
        name = "About"
        url = "/About-us"
        weight = 8

defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true

[Languages]
[Languages.en]
languageName = "English"
contentDir= "content/english"
weight=2

##
## the below is Chinese translation content
[Languages.zh]
languageName = "简体中文"
contentDir= "content/chinese"
weight=1
[Languages.zh.params]
  address = '中国广东省深圳市南山区学苑大道1088号南山智园A7栋1007'
  [Languages.zh.params.publications_selected]
    detailed_list = true
    title = "代表文章"
    subtitle = ""

  # Publications section.
  # Section will only be displayed if there are publications in `content/publication/`.
  [Languages.zh.params.publications]
    count = 5
    detailed_list = false
    title = "发表作品"
    subtitle = ""
    str_all = "更多作品"

  # Posts section.
  # Section will only be displayed if there are posts in `content/post/`.
  [Languages.zh.params.posts]
    count = 2
    title = "博客"
    subtitle = ""
    str_all = "更多"
    str_read_more = "更多"

  # Projects section.
  # Section will only be displayed if there are projects in `content/project/`.
  [Languages.zh.params.projects]
    title = "项目"
    subtitle = ""
    count = 4
    str_all = "更多"

  # Vacancies section
  # Section will only be displayed if there are valid vacancies in `content/vacancy`
#  [params.open_projects]
#    title = "Open projects"
#    subtitle = ""
#    count = 3
#    str_all = "All open projects"

  # Contact section.

  [Languages.zh.params.contact]
    enable = true
    title = "联系方式"
    subtitle = ""
    autolink = false  # Automatically link email and phone?

  # Navigation Links
  #   The weight parameter defines the order that the links will appear in.

  [[Languages.zh.menu.main]]
    name = "主页"
    url = "/zh/#home"
    weight = 1

  [[Languages.zh.menu.main]]
    name = "发表作品"
    url = "/zh/#publications"
    parent="research"
    weight = 2

  [[Languages.zh.menu.main]]
    name = "加入我们"
    url = "/zh/Join-us"

    weight = 6

  [[Languages.zh.menu.main]]
    name = "研究"
    url="/zh/#research"
    weight = 2
    identifier = "research"

  [[Languages.zh.menu.main]]
    name = "项目"
    url = "/zh/#projects"
    parent = "research"
    weight = 2


  [[Languages.zh.menu.main]]
    name = "团队成员"
    url = "/zh/#members"
    weight = 4



  [[Languages.zh.menu.main]]
    name = "Contact"
    url = "/zh/#contact"
    weight = 7

  [[Languages.zh.menu.main]]
    name = "教学"
    url = "http://mooc1.chaoxing.com/course/214395507.html"
    weight = 3

      [[Languages.zh.menu.main]]
        name = "关于"
        url = "/zh/About-us"
        weight = 8




